version: '3'

services:
  backend: 
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file: ./.env

# TODO