version: '3'

services:
  backend: 
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env

# TODO