query GetMe {
  getMe {
    _id
    email
    name
  }
}

query GetAuthUri($provider: String!) {
  getAuthUri(provider: $provider)
}

query ProviderCallback($provider: String!, $code: String!) {
  providerCallback(provider: $provider, code: $code) {
    _id
    email
    name
  }
}