fragment UserData on User {
	_id
  name
  email
  image
  roles
  createdAt
}

query GetMe {
  getMe {
    ...UserData
  }
}

query GetAuthUri($provider: String!) {
  getAuthUri(provider: $provider)
}

query ProviderCallback($provider: String!, $code: String!) {
  providerCallback(provider: $provider, code: $code) {
    ...UserData
  }
}

query UserWithEmailExists($email: String!) {
  userWithEmailExists(email: $email)
}

query GetEmailConfirmationMail($email: String!) {
  getEmailConfirmationMail(email: $email)
}

query GetUserById($id: String!) {
  getUserById(id: $id) {
    ...UserData
  }
}

mutation RegisterUser($input: CreateUserInput!) {
  registerUser(createUserInput: $input) {
    ...UserData
  }
}

mutation Login($input: LoginInput!) {
	login(loginInput: $input) {
		...UserData
  }
}

mutation Logout {
  logout
}

mutation VerifyCode($input: VerifyCodeInput!) {
  verifyCode(verifyCodeInput: $input)
}




mutation CreateQuiz($createQuizInput: CreateQuizInput!) {
  createQuiz(createQuizInput: $createQuizInput) {
    _id
    title
    questions {
      id
      text
      answerOptions {
        id
        text
      }
      correct
    }
    createdBy {
      ...UserData
    }
    createdAt
    updatedAt
  } 
}

query GetAllQuizzes {
  getAllQuizzes {
    _id
    title
    image
    createdBy {
      ...UserData
    }
    createdAt
    updatedAt
  } 
}

query GetQuizById($quizId: String!) {
  getQuizById(quizId: $quizId) {
    _id
    image
    title
    questions {
      id
      image
      text
      answerOptions {
        id
        image
        text
      }
    }
    createdBy {
      ...UserData
    }
    createdAt
    updatedAt
  } 
}